#!/bin/sh

#searches all subdirectories for bmp files starting with the first parameter
#and renames them replacing it with the second parameter leaving the suffix intact.

if [[ "$#" == 0 || "$#" == 1 && ("$1" == "-h" || "$1" == "--help") ]]; then 
    echo "usage: $0 oldprefix newprefix"
    echo ""
    echo "Searches all subdirectories for all files starting with the prefix"
    echo "given as the first parameter and renames them, substituting the old prefix with"
    echo "the new one, given as the second parameter. Any characters in the file name"
    echo "between the prefix and the extension are preserved."

elif [[ "$#" == 2 ]]; then
    find -name "$1*" -print0 | while IFS= read -r -d '' path; do
        name=`echo $path | sed -e "s|^\(.*\)/$1\([^/]*\)$|\1/$2\2|"`
        mv -v "$path" "$name";
    done
else
    for i in `seq 3 $#`; do
        find -name "$1*" -print0 | while IFS= read -r -d '' path; do
	    name=`echo $path | sed -e "s|^\(.*\)/$1\([^/]*\)$|\1/$2\2|"`
	    mv -v "$path" "$name"
	done
    done	    
fi

